name: Notify Parent Repository

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify parent repository update
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.NOTIFY_PARENT_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/CraigBanach/personal-site/dispatches \
            -d '{"event_type":"submodule-updated"}'
